= Mission briefing
:imagesdir: ../assets/images/

== Welcome to the Security Task Force

Welcome to the Security Task Force; please have a seat!

Last year we were exposed by a security breach on our platform.
The Security Task Force managed to trace back the actions taken by the hacker.
We identified that the hacker got access to one of our Tekton pipeline and used it to inject malicious code in one of our critical application.
We took action and re-enforced the security of our pipeline.

Yesterday, once again the Network & Security team reported a major incident on our line of production.
They claim that an application hosted on an OpenShift cluster was again compromised and important data might have been leaked from our databases.

We checked, and we are absolutely sure that that new hacker couldn't have tampered with our secured pipeline.
But we haven't been able to find the security hole that was exploited.

Again, we need your help in identifying the security weaknesses of our platform.
To support this, we've provided you with the account that all non-administrators use.
Believe me, if the hacker has got admin priviledges, we wouldn't even have this conversation.

Your objective, as a DevSecOps expert, is to perform the same actions the hacker did.
We know that the 'Customers' application is the one that was attacked.
Unfortunately, in the panic, the Infrastructure Security team destroyed the container image and the version of the application modified by the hacker disappeared, making our forensics much more difficult.
Anyway, we migrated out the Customers database so should the application run again, it wouldn't leak any sensitive information anymore.

Use the available tools to investigate.
We count on you!


== Starting your missions

Login to the CTF Dashboard with the link and credentials here below.  This is where you'll be able to see your missions and post your responses.
Some missions will be unlocked only once another one is complete, allowing you to progress into the main quest.
Extra missions can be fulfilled in parallel to the main quest.

Start by opening the Openshift web console.
You'll land in the namespace of the application that has been hacked.
You can notice that a pipeline has run, which created the malicious application, but the hacker, somehow, managed to destroy the image before leaving.
This explains why the Pod is not there.

Pay attention to the PipelineRun object.

Good luck!


====
https://ctfd-leaderboard.{openshift_cluster_ingress_domain}/challenges[CTF Dashboard^]

username: {user}

password: {password}

====


== Lab access

====
Login to the Openshift Web Console with RH SSO

https://{console_url}[Openshift Console^]

username: {user}

password: {password}


Login to ACS with Openshift SSO integration

https://central-stackrox.{openshift_cluster_ingress_domain}[Advanced Cluster Security for Kubernetes^]

username: {user}

password: {password}

====

====
Login to Openshift Gitops with the local authentication provider (NOT with Openshift SSO integration)

https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}[Openshift GitOps (ArgoCD)^]

username: {user}

password: {password}

====

====

{gitea_console_url}/gitea/customers-app.git[Source Code of the customers application^]

====


== Utilities
====
https://reqbin.com/[REST Client^]
====

== Documentation
====
https://quarkus.io/guides/openapi-swaggerui[Quarkus OpenAPI spec^]
====
