= {lab_name} : A Capture The Flag game.

This lab is a Capture The Flag (CTF) game.

The game is divided into mission and each mission ends when the mission flag is discovered.
A flag is an element of information related to security, such as a password, an IP address... 

This CTF game has a quest of 4 missions set in sequence (the next mission unlocks only when the previous one is complete)
and some extra missions that can be done in parallel to collect more points.

The briefing is described on the next page.
Missions'objectives are described directly on the Leaderboard.

== Winning the CTF

To win, you must collect a maximum number of points.
Each discovered flag brings you a certain amount of points:

Point Zero                  : 10 points

Code Red Quest
 - 1. Run !                 : 100 points

 - 2. Captain Hook          : 150 points

 - 3. Blind Test            : 80 points

 - 4. Pearl Harbour         : 200 points
 
 - 5. Inception             : 300 points

 - 6. I've got you babe     : 350 points

Side Missions
 - Grizzly Credentials      : 50 points

 - Chessmaster              : 50 points

 - Vault Tec                : 50 points

 - Moby-Dick                : 50 points

 - Hypotek                  : 50 points


In case of a tie, the fastest wins, so you also have to be fast !

To help you go faster, you can unlock mission's hints, but they will cost you some points.


